accounts/urls.py
from django.urls import path, include

from .views import SignUpFormView

app_name = 'accounts'

urlpatterns = [
    path('', include('django.contrib.auth.urls'), name='authentication'),
    path('sign_up/', SignUpFormView.as_view(), name='sign_up'),
]

note/urls.py
from django.urls import path
from django.views.generic import TemplateView, RedirectView
from django.urls import reverse

from .views import NoteCreateView, NoteDeleteView, NoteDetailView, NoteUpdateView, ListViewNote, HomeView

app_name = 'note'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('list/', ListViewNote.as_view(), name='list_view' ),
    path('new/', NoteCreateView.as_view(), name='create_note'),
    path('delete/<pk>/', NoteDeleteView.as_view(), name='delete_note'),
    path('update/<pk>/', NoteUpdateView.as_view(), name='update_note'),
    path('<pk>/', NoteDetailView.as_view(), name='detail_note'),
]

notes/urls.py
from django.contrib import admin
from django.urls import path, include
from django.urls.base import reverse_lazy
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('notes/', include('note.urls'), name='note'),
    path('accounts/', include('accounts.urls'), name='login'),
    path('', RedirectView.as_view(url=reverse_lazy('note:home'))),
]

accounts/models.py
from django.db import models

# Create your models here.

note/models.py
from django.db import models
from django.conf import settings



class Note(models.Model):
    title = models.CharField(max_length=80)
    user = models.ForeignKey(settings.AUTH_USER_MODEL , on_delete=models.CASCADE, null=True)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self) -> str:
        return self.title



class Tag(models.Model):
    note = models.ForeignKey(Note, on_delete=models.CASCADE)
    tag = models.CharField(max_length=40)

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model
from django.forms import EmailField

User = get_user_model()


class SignUpForm(UserCreationForm):
    email = EmailField(max_length=255, help_text='Valid email address')

    def send_success_email(self):
        with open('log.txt', 'w') as file:
            file.write('Sign Up Sucessfull')

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

note/forms.py
from django.forms import ModelForm

from .models import Note

class NoteForm(ModelForm):
    model = Note
    class Meta:
        include = ('title', 'content')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['title'].widget.attrs['class'] = 'note-title'
        self.fields['content'].widget.attrs['class'] = 'note-content'

accounts/views.py
from django.shortcuts import render
from django.views.generic.edit import FormView
from django.urls import reverse_lazy
from django.contrib.auth import login, authenticate
from .forms import SignUpForm

# Create your views here.


class SignUpFormView(FormView):
    form_class = SignUpForm
    template_name = 'registration/sign_up.html'
    success_url = reverse_lazy('note:home')

    def form_valid(self, form ):
        form.save()
        username = form.cleaned_data.get('username')
        password = form.cleaned_data.get('password1')
        user = authenticate(self.request, username=username, password=password)
        login(self.request, user)
        form.send_success_email()
        return super().form_valid(form)

note/views.py
from django.shortcuts import render
from django.views.generic import CreateView, UpdateView, ListView, DeleteView, DetailView, View
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin

# Create your views here.
from .models import Note

class HomeView(View):
    template_name = 'note/home.html'
    
    def get(self, request):
        return render(request, self.template_name)

class NoteCreateView(LoginRequiredMixin, CreateView):
    model = Note
    fields = ['title', 'content']
    success_url = reverse_lazy('note:home')
    initial = {
        'title': 'Title...',
        'content': 'Content of the note...'
    }


    def form_valid(self, form):
        obj = form.save(commit=False)
        obj.user = self.request.user
        return super().form_valid(form)



class NoteUpdateView(LoginRequiredMixin, UpdateView):
    model = Note
    fields = ['title', 'content']
    success_url = reverse_lazy('note:home')

    def get_queryset(self):
        query = super().get_queryset()
        return query.filter(user=self.request.user)
        

class NoteDeleteView(LoginRequiredMixin, DeleteView):
    model = Note
    success_url = reverse_lazy('note:home')


class NoteDetailView(LoginRequiredMixin, DetailView):
    model = Note


class ListViewNote(LoginRequiredMixin, ListView):
    model = Note
    paginate_by = 10

note/templates/note/home.html
{% extends 'base.html' %}

{% load humanize %}
{% load static %}


{% block css %}
    <link rel="stylesheet" href="{% static 'note/css/note.css' %}">
{% endblock css %}
    

{% block content %}
    <div class="container">
        <div class="list">
            {% block note_list %}
                <h1>Notes</h1>
                <h4><a href="{% url 'note:create_note' %}">Create Note</a></h4>
                {% if not my_notes %}
                    <p>Empty</p>
                {% else %}
                    {% for note in my_notes %}
                        <li class="card">
                            <p>{{ note.created_at|naturaltime }}</p>
                            <h3 class="card-title"><a href="{% url 'note:update_note' note.id %}">{{ note.title }}</a></h3>
                            <p><a href="{% url 'note:delete_note' note.id %}">Delete</a></p>
                        </li>
                        <br>
                    {% endfor %}
                {% endif %}
            {% endblock note_list %}
        </div>
        
        <div class="note">
            {% block note %}
                <h1><h3>Welcome to Note app. Create account or note to start.</h3></h1>
            {% endblock note %}
        </div>
    </div>
{% endblock content %}

note/templates/note/note_confirm_delete.html
{% extends 'base.html' %}


{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        <p>Are you sure you want to delete {{ object }}</p>
        <input type="submit" value="Confirm">
    </form>
{% endblock content %}
    

note/templates/note/note_detail.html
{% extends 'base.html' %}


{% block content %}
    <h3>{{ object.title }}</h3>
    <textarea name="" id="" cols="30" rows="10">{{ object.content }}</textarea>   
{% endblock content %}

    

note/templates/note/note_form.html
{% extends 'note/home.html' %}

{% block note %}
    <form action="" method="POST" class="note-form" autocomplete="off">
        {% csrf_token %}
        <div class="note-container">
            {{ form.title }}
            {{ form.content }}
        </div>
        <button class="btn btn-primary" type="submit">Save</button>
    </form>
{% endblock note %}

note/templates/note/note_list.html
{% load humanize %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Notes</h1>
    <h4><a href="{% url 'note:create_note' %}">Create Note</a></h4>
    {% for note in object_list %}
        <li>
            <p>{{ note.created_at|naturaltime }}</p>
            <h3><a href="{% url 'note:update_note' note.id %}">{{ note.title }}</a></h3>
            <p><a href="{% url 'note:delete_note' note.id %}">Delete</a></p>
        </li>
        <br>
    {% endfor %}  
</body>
</html>

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>


    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <link rel="stylesheet" href="{% static 'note/css/grid.css' %}">
    
    {% block css %}
    {% endblock css %}
        
    <title>
    {% block title %}
        NOTE
    {% endblock title %}
    </title>
</head>
<body>
    <nav>
        {% block nav %}
            {% if user.is_authenticated %}
                <div class="avatar">
                    <h3>{{ user.username }}</h3>
                    <a href="{% url 'accounts:logout' %}">Log Out</a>
                </div>
            {% else %}
                <div>
                    <h3><a href="{% url 'accounts:login' %}">Log In</a></h3>
                    <p>Dont have an account? <a href="{% url 'accounts:sign_up' %}">Sign Up Here</a></p>
                </div>
            {% endif %}
        {% endblock nav %}
    </nav>
    {% block content %}
        <p>Change the content!</p>
    {% endblock content %}  
</body>
</html>